### ISSUE TITLE
FR: add number base conversion

### ISSUE THREAD

**Issue by sljeff** [hj24/Convertor#8]
like `hex->decimal` / `decimal -> hex` / `decimal -> binary`

**Comment by hj24** [comment]
@sljeff

**Comment by sljeff** [comment]
looks TQL to me

**Comment by hj24** [comment]
@sljeff 更新上线了，可以试试看 https://chrome.google.com/webstore/detail/parse-diff-tool/plldopcffknjbimajdlcakmlgimfofcf
